-- MySQL Script generated by MySQL Workbench
-- Sun Feb  9 20:30:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pacote_de_viagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pacote_de_viagem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pacote_de_viagem` (
  `id_pacote` INT NULL AUTO_INCREMENT,
  `duração_dias` INT NOT NULL,
  `id_destino` INT NOT NULL,
  PRIMARY KEY (`id_pacote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orçamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orçamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orçamento` (
  `id_orcamento` INT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `id_pacote` INT NOT NULL,
  `id_agente` INT NOT NULL,
  PRIMARY KEY (`id_orcamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Agente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Agente` (
  `idAgente` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `Orçamento_id_orcamento` INT NOT NULL,
  PRIMARY KEY (`idAgente`),
  INDEX `fk_Agente_Orçamento1_idx` (`Orçamento_id_orcamento` ASC) VISIBLE,
  CONSTRAINT `fk_Agente_Orçamento1`
    FOREIGN KEY (`Orçamento_id_orcamento`)
    REFERENCES `mydb`.`Orçamento` (`id_orcamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id_cliente` INT NULL,
  `email` VARCHAR(100) NOT NULL,
  `pacote_de_viagem_id_pacote` INT NOT NULL,
  `Agente_idAgente` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Cliente_pacote_de_viagem_idx` (`pacote_de_viagem_id_pacote` ASC) VISIBLE,
  INDEX `fk_Cliente_Agente1_idx` (`Agente_idAgente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_pacote_de_viagem`
    FOREIGN KEY (`pacote_de_viagem_id_pacote`)
    REFERENCES `mydb`.`pacote_de_viagem` (`id_pacote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Agente1`
    FOREIGN KEY (`Agente_idAgente`)
    REFERENCES `mydb`.`Agente` (`idAgente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Destino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Destino` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Destino` (
  `id_destino` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(50) NOT NULL COMMENT 'O destino possui nome e país.',
  `pacote_de_viagem_id_pacote` INT NOT NULL,
  PRIMARY KEY (`id_destino`),
  INDEX `fk_Destino_pacote_de_viagem1_idx` (`pacote_de_viagem_id_pacote` ASC) VISIBLE,
  CONSTRAINT `fk_Destino_pacote_de_viagem1`
    FOREIGN KEY (`pacote_de_viagem_id_pacote`)
    REFERENCES `mydb`.`pacote_de_viagem` (`id_pacote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contato_Agente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contato_Agente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contato_Agente` (
  `id_cliente` INT NOT NULL,
  `id_agente` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `id_agente`),
  CONSTRAINT `fk_cliente_agente`
    FOREIGN KEY (`id_cliente` , `id_agente`)
    REFERENCES `mydb`.`Agente` (`idAgente` , `idAgente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_agente`
    FOREIGN KEY (`id_cliente` , `id_agente`)
    REFERENCES `mydb`.`Cliente` (`id_cliente` , `Agente_idAgente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_Pacote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente_Pacote` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente_Pacote` (
  `id_cliente` INT NULL,
  `id_pacote` INT NULL,
  PRIMARY KEY (`id_cliente`, `id_pacote`),
  INDEX `fk_cliente_pacote_pacote_idx` (`id_pacote` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_pacote_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_pacote_pacote`
    FOREIGN KEY (`id_pacote`)
    REFERENCES `mydb`.`pacote_de_viagem` (`id_pacote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
